### ISSUE TITLE
Crash in [MQTTCoreDataFlow initWithContext:andObject:] 

### ISSUE THREAD

**Issue by scarlett628** [novastone-media/MQTT-Client-Framework#157]
Hi @ckrey 
I had updated MQTT-Client-Framework to 0.7.7, and received some crash as follows:
![image](https://cloud.githubusercontent.com/assets/4434295/16006115/dba808bc-319d-11e6-9fb4-8e21ef07223b.png)
When app becomes active, we send an online message to server after connected with MQTT service.When app resigns active,we also send an offline message to server before breaking with MQTT service.So the app crash in these time occasionally. I don't know why these happend, can you help me?
 Thanks :）

**Comment by scarlett628** [comment]
Hi @ckrey ~
The crash rate is increasing because of the reason. Do you have any suggestion? We will be grateful for that.

**Comment by sudotamm** [comment]
Hi @ckrey ,

I aslo got this issue in version 0.7.9. Did it resolved yet? Any suggestion will be very grateful.

**Comment by ckrey** [comment]
I did a lot of de-buggung work with regards to CoreDataPersistence. Are your problems still happening?

**Comment by corymsmith** [comment]
I'm seeing this in an app I developed as well.

**Comment by Gavin-Zhou** [comment]
I got sam issue in version 0.8.7

**Comment by Gavin-Zhou** [comment]
I got the same issue in version 0.8.7
![bc6d0865-a7f3-4a67-8046-bad7e5db0118](https://user-images.githubusercontent.com/13465778/28814957-385e4420-76d2-11e7-9bc6-36e762f5f29c.png)

**Comment by jcavar** [comment]
This could be fixed with https://github.com/ckrey/MQTT-Client-Framework/pull/375

**Comment by pantaopt** [comment]
@niuhongwei

**Comment by pantaopt** [comment]
@niuhongwei @ckrey @jcavar  hi，can you tell me what caused this crash？

**Comment by pantaopt** [comment]
@sudotamm  hello, can you tell me what caused this crash?

**Comment by sudotamm** [comment]
@pantaopt plz refer to #375

**Comment by jcavar** [comment]
I believe this should be fixed, please try latest version and feel free to reopen if it is not.
