### ISSUE TITLE
Library get freeze in publishAndWaitData

### ISSUE THREAD

**Issue by OmidID** [novastone-media/MQTT-Client-Framework#164]
Hello. 
After I had update the library when I call 2 or 3 time publishAndWaitData it's will be freeze.
Before update it was worked perfectly with same code!
I try to debug and i realized it's will be waiting for AK from server.

```

while (self.synchronPub && (timeout == 0 || [started timeIntervalSince1970] + timeout > [[NSDate date] timeIntervalSince1970])) {
      DDLogVerbose(@"[MQTTSessionSynchron] waiting for mid %d", mid);
      [[NSRunLoop currentRunLoop] runUntilDate:[NSDate dateWithTimeIntervalSinceNow:.1]];
}
```

**Comment by OmidID** [comment]
Now after I research about this problem I realized the library does not receive any AK after 1 time.

```
public func messageDelivered(session: MQTTSession!, msgID: UInt16) {
   print("-> Message delivered - AK - \(msgID)")
}
```

**Comment by OmidID** [comment]
After I start debug it I found the problem coming from here:
MQTTCoreDataPersistence.m - internalFlowForClientId

```
- (MQTTCoreDataFlow *)internalFlowForClientId:(NSString *)clientId
                                 incomingFlag:(BOOL)incomingFlag
                                    messageId:(UInt16)messageId {
    MQTTCoreDataFlow *flow = nil;

    DDLogVerbose(@"flowforClientId performing");

    NSFetchRequest *fetchRequest = [NSFetchRequest fetchRequestWithEntityName:@"MQTTFlow"];
    fetchRequest.predicate = [NSPredicate predicateWithFormat:
                              @"clientId = %@ and incomingFlag = %@ and messageId = %@",
                              clientId,
                              @(incomingFlag),
                              @(messageId)
                              ];
    NSArray *rows;
    NSError *error = nil;
    rows = [self.managedObjectContext executeFetchRequest:fetchRequest error:&error];
    if (!rows) {
        DDLogError(@"[MQTTPersistence] flowForClientId %@", error);
    } else {
        if ([rows count]) {
            flow = [[MQTTCoreDataFlow alloc] initWithContext:self.managedObjectContext andObject:[rows lastObject]];
        }
    }
    return flow;
}
```

The "rows" will be empty after execute.

**Comment by OmidID** [comment]
@ckrey After I switched to MQTTInMemoryPersistence the problem was solved. But of course for temporary. Finally I didn't realized what is the problem exactly. Sorry about that. I hope you find the problem soon :)

**Comment by ckrey** [comment]
What OS and version are you working on (iOS, tvOS, macOS)?
What is your broker and version?

**Comment by OmidID** [comment]
@ckrey Thanks for your reply 
I using iOS v9 (Swift) and I use our own custom MQTT server. But I try with public broker too and same result:

http://test.mosquitto.org/

**Comment by jcavar** [comment]
This could be fixed with https://github.com/ckrey/MQTT-Client-Framework/pull/375

**Comment by jcavar** [comment]
I believe this should be fixed, please try latest version and feel free to reopen if it is not.
