### ISSUE TITLE
kSecTrustResultRecoverableTrustFailure, No Error report

### ISSUE THREAD

**Issue by zhouhaoranxin** [novastone-media/MQTT-Client-Framework#189]
static BOOL SSLServerTrustIsValid(SecTrustRef serverTrust) {
    BOOL isValid = NO;
    SecTrustResultType result;
    __Require_noErr_Quiet(SecTrustEvaluate(serverTrust, &result), _out);

```
isValid = (result == kSecTrustResultUnspecified      // The OS trusts this certificate implicitly.
            || result == kSecTrustResultProceed);    // The user explicitly told the OS to trust it.

// else?  It's somebody else's key. Fall immediately.

_out:
return isValid;
```

}

**# vvvvvvvvv
if  result==kSecTrustResultRecoverableTrustFailure  this will return NO**
- (BOOL)evaluateServerTrust:(SecTrustRef)serverTrust
                forDomain:(NSString *)domain
  {
  NSMutableArray *policies = [NSMutableArray array];
  if (self.validatesDomainName) {
      [policies addObject:(__bridge_transfer id)SecPolicyCreateSSL(true, (__bridge CFStringRef)domain)];
  } else {
      [policies addObject:(__bridge_transfer id)SecPolicyCreateBasicX509()];
  }
  
  SecTrustSetPolicies(serverTrust, (__bridge CFArrayRef)policies);
  
  if (self.SSLPinningMode == MQTTSSLPinningModeNone) {
      return self.allowInvalidCertificates || SSLServerTrustIsValid(serverTrust);
  }
  // if client didn't allow invalid certs, it must pass CA infrastructure
  else if (!SSLServerTrustIsValid(serverTrust) && !self.allowInvalidCertificates) {
      return NO;
  }
  
  NSArray *serverCertificates = SSLCertificateTrustChainForServerTrust(serverTrust);
  switch (self.SSLPinningMode) {
      case MQTTSSLPinningModeNone:
      default:
          return NO;
      case MQTTSSLPinningModeCertificate: {
          NSMutableArray *pinnedCertificates = [NSMutableArray array];
          for (NSData *certificateData in self.pinnedCertificates) {
              @try {
                  [pinnedCertificates addObject:(__bridge_transfer id)SecCertificateCreateWithData(NULL, (__bridge CFDataRef)certificateData)];
              } @catch (NSException *exception) {
                  //fix issue #151, if the pinnedCertification is not a valid DER-encoded X.509 certificate, for example it is the PEM format, SecCertificateCreateWithData will return nil, and application will crash
                  if ([exception.name isEqual:NSInvalidArgumentException]) {
                      return NO;
                  }
              }
          }
          SecTrustSetAnchorCertificates(serverTrust, (__bridge CFArrayRef)pinnedCertificates);
  
  ```
      if (!SSLServerTrustIsValid(serverTrust)) {
          return NO;
      }
  ```

**vvvvvvvvvvvvvvvvvvvvvvv
will return NO**
- (BOOL)applySSLSecurityPolicy:(NSStream *)writeStream withEvent:(NSStreamEvent)eventCode;
  {
  if(!self.securityPolicy){
      return YES;
  }
  
  if(self.securityPolicyApplied){
      return YES;
  }
  
  SecTrustRef serverTrust = (__bridge SecTrustRef) [writeStream propertyForKey: (__bridge NSString *)kCFStreamPropertySSLPeerTrust];
  if(!serverTrust){
      return NO;
  }
  
  self.securityPolicyApplied = [self.securityPolicy evaluateServerTrust:serverTrust forDomain:self.securityDomain];
  return self.securityPolicyApplied;
  }

**vvvvvvvvvvvvvvvvvvvvvvvv
will return NO**
- (void)stream:(NSStream*)sender handleEvent:(NSStreamEvent)eventCode {
  
  if (eventCode & NSStreamEventHasSpaceAvailable) {
      DDLogVerbose(@"[MQTTCFSocketEncoder] NSStreamEventHasSpaceAvailable");
      if(![self applySSLSecurityPolicy:sender withEvent:eventCode]){
          self.state = MQTTCFSocketEncoderStateError;
          self.error = [NSError errorWithDomain:@"MQTT"
                                           code:errSSLXCertChainInvalid
                                       userInfo:@{NSLocalizedDescriptionKey: @"Unable to apply security policy, the SSL connection is insecure!"}];
      }
  }
  [super stream:sender handleEvent:eventCode];
  }

**vvvvvvvvvvvvvv
in this function self.state been set to MQTTCFSocketEncoderStateError;**
- (void)stream:(NSStream*)sender handleEvent:(NSStreamEvent)eventCode {
  
  if (eventCode & NSStreamEventOpenCompleted) {
      DDLogVerbose(@"[MQTTCFSocketEncoder] NSStreamEventOpenCompleted");
  
  }
  if (eventCode & NSStreamEventHasBytesAvailable) {
      DDLogVerbose(@"[MQTTCFSocketEncoder] NSStreamEventHasBytesAvailable");
  }
  
  if (eventCode & NSStreamEventHasSpaceAvailable) {
      DDLogVerbose(@"[MQTTCFSocketEncoder] NSStreamEventHasSpaceAvailable");
      if (self.state == MQTTCFSocketEncoderStateInitializing) {
          self.state = MQTTCFSocketEncoderStateReady;
          [self.delegate encoderDidOpen:self];
      }
  
  ```
  if (self.state == MQTTCFSocketEncoderStateReady) {
      if (self.buffer.length) {
          [self send:nil];
      }
  }
  ```
  
  }

but in this function
        if (self.state == MQTTCFSocketEncoderStateInitializing) {
            self.state = MQTTCFSocketEncoderStateReady;
            [self.delegate encoderDidOpen:self];
        }

```
    if (self.state == MQTTCFSocketEncoderStateReady) {
        if (self.buffer.length) {
            [self send:nil];
        }
    }
```

vvvvvvvvvvv
**just have self.state == MQTTCFSocketEncoderStateInitializing /self.state == MQTTCFSocketEncoderStateReady**

**Comment by jcavar** [comment]
@ckrey @zhouhaoranxin can you please explain more in detail what is bug here?

**Comment by jcavar** [comment]
I will close this for now as we are missing information. Feel free to reopen.
