### ISSUE TITLE
Run in background thread

### ISSUE THREAD

**Issue by dimohamdy** [novastone-media/MQTT-Client-Framework#276]
I want to run  Session in background thread in swift using DispatchQueue
i try to make it but the delegate function not fired

**Comment by ckrey** [comment]
Create MQTTSession in the same thread as you are doing the connect, publish etc. and  have a look at the examples here https://github.com/ckrey/MQTT-Client-Framework/blob/master/MQTTClient/MQTTClientTests/MQTTTestMultiThreading.m

**Comment by dimohamdy** [comment]
can we change library to work in different threads without the hassle of reserve connection thread ?

**Comment by ckrey** [comment]
@dimohamdy I don't have the resources to undertake that, but I am happy to cooperate

**Comment by jcavar** [comment]
Creating MQTTSession in same thread is not enough. There is still work required to maintain threads run loop running. I think we implemented this successfully in the end but it is really hassle. There are just too many details to implement this correctly when using `NSThread` interface. E.g. see (this)[http://blog.csdn.net/martin_liang/article/details/43151255]

Ideally as @dimohamdy suggested I think we want to pass custom queue on which we want `MQTTClient` to do work. I am not familiar with lower level details of this framework, but how hard would be to migrate to something like (this in AFNetworking)[https://github.com/AFNetworking/AFNetworking/blob/2.6.3/AFNetworking/AFURLRequestSerialization.m#L468-L503]

**Comment by jcavar** [comment]
This is now implemented on master. You can pass `DispatchQueue` to `MQTTSession`. There are some bits to resolve before making official release for this but you can try it out from master if you want.

**Comment by gsaputelli** [comment]
do you have an example of using mqttsession with background threads? when will the version be available on cocoapods ?

**Comment by jcavar** [comment]
There is new parameter in `MQTTSession` initializer, e.g:
https://github.com/novastone-media/MQTT-Client-Framework/blob/master/MQTTClient/MQTTClient/MQTTSessionLegacy.h#L54

where you just pass your desired queue.

I don't have estimate when this will be available on CocoaPods, I want to do some clean up first before doing that, but we use it from master and works well for us.

**Comment by jcavar** [comment]
Ok, 0.10.0 version is on CocoaPods which adds support for this. Please give it a try.
