### ISSUE TITLE
[MQTTDecoder] oops received (67)=<35d80200

### ISSUE THREAD

**Issue by willem4ever** [novastone-media/MQTT-Client-Framework#397]
Error message when having more as two retained messages.

When I have at least 3 retained messages, I get the oops received on subscribe, the message doesn't happen when I have 0-2 retained message for the topic I subscribe to.

**Comment by jcavar** [comment]
Would it be possible to add test case for this? Could this be related to broker you are using?

**Comment by ckrey** [comment]
This is not an error, just a warning that the buffer does not contain the whole message

**Comment by willem4ever** [comment]
That makes sense, thanks for explaining.
