### ISSUE TITLE
can not receiving mqtt message while app is in background

### ISSUE THREAD

**Issue by RajaReddyIOS** [novastone-media/MQTT-Client-Framework#398]
mqtt didreceive message is not being called when app is in background and terminated and when device is lock

**Comment by jcavar** [comment]
Depending on how you use MQTTClient, background messages should work (unless you are turning it off manually). When app is terminated messages should not be received, that is just how iOS works.

**Comment by RajaReddyIOS** [comment]
if (!self.sessionManager.requiresTearDown) {
        // we don't want to tear down session as it's already closed
        return;
}
can you say what is use of this code on "ForegroundReconnection" this class
