### ISSUE TITLE
stay connected while app terminating also

### ISSUE THREAD

**Issue by RajaReddyIOS** [novastone-media/MQTT-Client-Framework#399]
how to stay connected with mqtt while app is terminated also
i need to get messages while app is killed also
is their any way to do this?
thank you in advance
hope i get solution...

**Comment by ckrey** [comment]
MQTT on iOS is always part of an app.

You either keep the app running in the background (see Apple's docs under which circumstances you get permission to do that) or you use Apple's APNS framework

**Comment by RajaReddyIOS** [comment]
what do you mean we can't use or we can
thank you

**Comment by willem4ever** [comment]
Your app needs to be running to stay connected with MQTT. When your apps terminates you will also lose your connection, this is how IOS works nothing you can change about that.

**Comment by RajaReddyIOS** [comment]
how android is alive always?
we can't make like android..
i need to stay connected with mqtt(keep alive always even app killed )

**Comment by jcavar** [comment]
As far as I know Android allows apps to have associated background service that is running while app does not. I assume that is how it works on Android. iOS doesn't have that mechanism so as others suggested you can either make sure app is running in background (this depends on type of your app) or use push notifications to achieve your goal.
