### ISSUE TITLE
Push Notification using

### ISSUE THREAD

**Issue by RajaReddyIOS** [novastone-media/MQTT-Client-Framework#405]
internally this library is using push notification to reconnect after app killed...
how to reconnect mqtt client after app killed?
is their any way to stay connected with web-socket?
how to keep alive device with mqtt like in android..
is it posible on ios

**Comment by genMY** [comment]
because in<ForegroundReconnection.m> add <UIApplicationWillResignActiveNotification> notice ,so app backgroud MQTT disconnect, solve : copy code : modify here.

**Comment by cszwdy** [comment]
666

**Comment by jcavar** [comment]
Can you please be more specific about your issue?
