### ISSUE TITLE
'Timer' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by mn288** [novastone-media/MQTT-Client-Framework#407]
Hello, 

When using the newest Pod on Xcode 9.1, and using a Timer value in the class I am using, a clash happens in:

'Timer' is ambiguous for type lookup in this context

Timer is a protected class under the Swift Language and clashing with your **Timer.h** and **Timer.m** files. I refactored the names on your library and all works well

**Comment by jcavar** [comment]
Version 0.10.1 is out that fixes this. Thanks for reporting!
