### ISSUE TITLE
Linker Error for React-native project.

### ISSUE THREAD

**Issue by manju-ms** [novastone-media/MQTT-Client-Framework#408]
I have included the MQTT for my react-native project.
 
1) Through coco-pods,   i have include the pod mqttclient in pod fail and did pod update.
2) After that building the app for archive i will get the Linker error. 
3) After that i tried manually linking the mqtt project source files to my project by drag and droping the mqtt folder to my project root path.
4) Next i added SRWebSocket folder inside the MQTT.
5) After running the project i am getting the same error as linker error. 

can you guide me where i am doing wrong? 
 
In documentation there is another way of including through framework which is MqttClient.framework,  where will be this framework file  so that i will include this file.

**Comment by jcavar** [comment]
What kind of linker error are you getting?

**Comment by jcavar** [comment]
I will close this due to inactivity. Feel free to reopen with more info if you still have an issue.
