### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by jhoongo** [novastone-media/MQTT-Client-Framework#410]
Hi,

I would like to ask some questions regarding the license of MQTT-Client-Framework.
As I am reviewing the product, and release tab on GitHub repository, there are few binaries, and/or files that are under GPL such as Doxygen, and jQuery.

Since the project itself is licensed under EPL, I'm little bit confused on this license.
I do see that actual binary distributed through CocoaPod does not contain Doxygen and jQuery as they are related to documentation, but I do see it on Github's release page.

Could you please clarify the license in such case?

**Comment by JackLeo** [comment]
Doxygen and jQuery are only used by auto-generated documentation that has been committed to the source code. It looks like a committed build artefact.

Given that it's auto-generated probably the best course of action is to remove it and start building docs via the pipeline if they are of any use or just start expanding docs via the GitHub wiki. This way,  any licensing ambiguities should disappear and the code would not be littered with build artefacts.

Does anyone find value in the docs being there right now?

**Comment by jcavar** [comment]
`dist` is now removed from source code so next release should not contain any Doxygen or jQuery.

Thanks!
