### ISSUE TITLE
will message not publishing proper

### ISSUE THREAD

**Issue by RajaReddyiOS** [novastone-media/MQTT-Client-Framework#419]
will message is not properly publishing after logout
but when i turn off wifi or no network then will message is publishing properly
the only issue is on logout

**Comment by ckrey** [comment]
Please read the MQTT 3.1.1 spec: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.pdf

The will message is not sent on DISCONNECT (what you call logout) by the protocol.
If you want a special message to be sent before you DISCONNECT, you have to do this explicitly.

**Comment by RajaReddyIOS** [comment]
mqtt is disconnecting automatically and trying to reconnecting.. it has occurring every 2 mins 
am using sessionManager for connection

**Comment by jcavar** [comment]
I will close this due to inactivity. Feel free to reopen this if you have any more info.
