### ISSUE TITLE
MQTT nextMsgId Freezes iOS app

### ISSUE THREAD

**Issue by umer-sufyan** [novastone-media/MQTT-Client-Framework#421]
Hi, I am facing bit of strange issue , some time my app gets stuck on debugging i got that MQtt NextMsgID is causing that freeze, could you please suggest any work around for that.

**Comment by umer-sufyan** [comment]
Perhaps we need to subscribe topics in dispatch thread, Something like that?

`dispatch_async(dispatch_get_main_queue(), ^(void) {
        [_mqttClass subscribeFeedMQtt:feedid];
    });`

**Comment by jcavar** [comment]
Which version of MQTT-Client-Framework are you using?

**Comment by umer-sufyan** [comment]
i have been updating my pod, so it should be latest, but seems like problem has been solved dispatch_async , after that i did not face that issue though. i am leaving this open till, as i am not sure, 
about freezing still! but so far so good, i just checked now, i did not face, usually i faced when my app resume from background.

**Comment by umer-sufyan** [comment]
I think you can find out that freeze with low network/bandwidth, what i did to check before subscribing if it is connected then only if only it is connected then go for subscribe, with low bandwidth , due to fluctuation of net , it might be in connecting stat most of the time that could cause freeze, not sure, but it is not happening to me any more with that trick ;) I am going to close this issue.
