### ISSUE TITLE
No obvious way to set SSL / TLS cipher

### ISSUE THREAD

**Issue by wesdyoung** [novastone-media/MQTT-Client-Framework#423]
Looking through the API docs I cannot see a way to set the SSL / TLS ciphers or version.  The client connects using SSL3 even though the Mosquitto broker TLS cipher is set to TLSv1.2 (and SSL2 and SSL3 is disabled: `ciphers TLSv1.2:!aNULL:!eNULL:!LOW:!EXPORT:!SSLv2:!SSLv3:@STRENGTH`).

**Comment by jcavar** [comment]
You are right. This is definitely something that we should support.

**Comment by JackLeo** [comment]
As a potential workaround, you can proxy the connection through load balancer of some sorts and do the SSL termination there. In such case, you should be able to limit the SSL / TLS cyphers or version used given it's provided by the load balancer tech.

**Comment by jcavar** [comment]
Released 0.12.0. You can now set this property on `MQTTSession` but I think something is weird in your setup as well. If broker doesn't support SSLv3 then client should not be able to connect to it.
