### ISSUE TITLE
Some things to consider:

### ISSUE THREAD

**Issue by rurza** [novastone-media/MQTT-Client-Framework#428]
- [mark a method as a deprecated before removing](https://stackoverflow.com/questions/3908715/how-do-i-flag-a-method-as-deprecated-in-objective-c-2-0)

- [semantic versioning](https://semver.org)

**Comment by jcavar** [comment]
Hi, thanks for your suggestions. While I do generally agree with you, we are at the moment in `0.` stage of project and I think it is ok if we from time to time break some APIs. Also there are a lot of not needed APIs that make project more complex and hard to maintain so we are trying to remove them.

With recent API removals no functionality was changed or removed so I think process of upgrading was straightforward?

I believe it is in best interest of this project and community to get rid of unnecessary complexity as soon as possible.

**Comment by rurza** [comment]
> I believe it is in best interest of this project and community to get rid of unnecessary complexity as soon as possible.

👍

**Comment by JackLeo** [comment]
Related https://github.com/novastone-media/MQTT-Client-Framework/issues/415
