### ISSUE TITLE
Warning: deprecations

### ISSUE THREAD

**Issue by wenxin3262** [novastone-media/MQTT-Client-Framework#430]
`/Pods/MQTTClient/MQTTClient/MQTTClient/MQTTCFSocketTransport.m:113:23: 'dispatch_get_current_queue' is deprecated: first deprecated in iOS 6.0 - unsupported interface`
`/Pods/MQTTClient/MQTTClient/MQTTClient/MQTTDecoder.m:69:23: 'dispatch_get_current_queue' is deprecated: first deprecated in iOS 6.0 - unsupported interface`

**Comment by jcavar** [comment]
Thanks for reporting, this has been fixed on master and will be available in next release

**Comment by jcavar** [comment]
Released 0.12.0
