### ISSUE TITLE
Inject URL in MQTTWebsocketTransport

### ISSUE THREAD

**Issue by lagnat** [novastone-media/MQTT-Client-Framework#433]
I imagine I might have to provide an Authorization header or supply the signature in the URL.  It this known to work or not work?

**Comment by lagnat** [comment]
I'll answer my question in case anyone else wants to do this.

The solution is to sign the URL with SigV4 as described [here](https://docs.aws.amazon.com/iot/latest/developerguide/protocols.html).  The next problem is to be able to provide the URL to MQTTWebsocketTransport, rather than let MQTTWebsocketTransport construct the url itself.  That was accomplished with the following subclass.  

```
@interface MQTTWebsocketIoTTransport : MQTTWebsocketTransport
@property (nonatomic, retain) NSString *url;
@end

@implementation MQTTWebsocketIoTTransport

- (NSURL*) endpointURL {
    NSURL *url = [NSURL URLWithString:self.url];
    return url;
}

```

I'd be happy to contribute the SigV4 code if you think it makes sense in this framework.

**Comment by jcavar** [comment]
Hi @lagnat. Thanks for this. I think it makes sense that you are able to provide custom url instead of framework constructing it for you. 
With that we should be also able to get rid of few parameters which will simplify API.

**Comment by jcavar** [comment]
So for now, I would suggest to only implement this so you don't need your custom subclass. For SigV4 part I would rather leave it out to avoid additional complexity, but it would be nice to document it if someone else needs it.

**Comment by mendirattanishant** [comment]
@lagnat how did you inject this URL to WSSTransport layer after subclassing?

**Comment by lagnat** [comment]
More or less like this:

>       MQTTWebsocketIoTTransport *transport = [[MQTTWebsocketIoTTransport alloc] init];
>       transport.url = @" the url ";
> 
>        MQTTSession  *client = [[MQTTSession alloc] init];
>        client.transport = transport;
>        client connectAndWaitTimeout:30];

**Comment by yusufonderd** [comment]
Hi @lagnat  I need to MQTTWebsocketIoTTransport class. Can you help me ? I have a presigned url and I can't use it.

**Comment by jcavar** [comment]
Which part do you have problem with?

**Comment by jcavar** [comment]
Yes, Swift will as well require you to add override in front of function.

**Comment by yusufonderd** [comment]
MQTTWebsocketTransport object doesn't contains endpointURL function. You can check from source code: https://github.com/novastone-media/MQTT-Client-Framework/blob/fad0943ddc1c96b5cecc68314f540ac1097b870e/MQTTClient/MQTTClient/MQTTWebsocketTransport/MQTTWebsocketTransport.h

**Comment by lagnat** [comment]
[https://github.com/novastone-media/MQTT-Client-Framework/blob/fad0943ddc1c96b5cecc68314f540ac1097b870e/MQTTClient/MQTTClient/MQTTWebsocketTransport/MQTTWebsocketTransport.m#L52](url)

**Comment by yusufonderd** [comment]
Thank you now I edited subsclass as below  : 

```
class MQTTWebsocketIoTTransport: MQTTWebsocketTransport {
    var url : String = ""
    func endpointURL() -> NSURL {
        return NSURL(string: url)!
    }
}

```
Then I tried to connect : 
              ```
 let transport = MQTTWebsocketIoTTransport()
                transport.url = websocketUrl
                let  client = MQTTSession()
                client?.transport = transport;
                client?.clientId = clientID
                client?.delegate = self
                client?.connectionHandler = { session in
                    print("session:\(session)")
                }
                client?.connectAndWaitTimeout(10)
```
And I show this logs : 

> [MQTTSession] init
> [MQTTSession] connecting
> [MQTTSessionSynchron] waiting for connect
> [MQTTSessionSynchron] waiting for connect
> [MQTTSessionSynchron] waiting for connect
> [MQTTSessionSynchron] waiting for connect
> [MQTTSessionSynchron] waiting for connect
> [MQTTSessionSynchron] waiting for connect
> [MQTTSessionSynchron] waiting for connect
> [MQTTSessionSynchron] waiting for connect
> [MQTTSessionSynchron] waiting for connect
> [MQTTSessionSynchron] waiting for connect
> [MQTTSessionSynchron] waiting for connect
> [MQTTSessionSynchron] waiting for connect
> [MQTTSessionSynchron] waiting for connect
> [MQTTSessionSynchron] waiting for connect
> [MQTTSessionSynchron] waiting for connect
> [MQTTSessionSynchron] waiting for connect
> [MQTTSessionSynchron] waiting for connect
> [MQTTSessionSynchron] waiting for connect
> [MQTTSessionSynchron] waiting for connect
> [MQTTSessionSynchron] end connect
>

**Comment by mendirattanishant** [comment]
@yusufonderd  did subclassing actually call your `endpointURL `method? I put a break point and it was never called. Can you try?

**Comment by yusufonderd** [comment]
@mendirattanishant  You are right. endPointURL method never called.

**Comment by jcavar** [comment]
I think this might be due to Swift bridging.

**Comment by jcavar** [comment]
I am not sure what is best solution for this but it seems like a lot of people have this issues. So as a temporary workaround I would suggest that we introduce `endpointURL` property and in internal method we check if that property is set and return value or construct it if not.

PR with this would be appreciated.

**Comment by mendirattanishant** [comment]
@yusufonderd  
okay. I have a solution. pleas try this.I faced the same problem. I customized the framework for my needs. I solved it like this: 



I created a new property `NSString *url;` in `MQTTWebsocketTransport.h`. 

```
/** url an NSString containing the websocketurl
 * defaults to @""
 */
@property (strong, nonatomic) NSString *url;
```

I changed the implementation of method `open` in `MQTTWebsocketTransport.m` to create `NSMutableURLRequest` object using url specified. 
```

- (instancetype)init {
    self = [super init];
    self.url = @"";
    self.host = @"localhost";
    self.port = 80;
    self.path = @"/mqtt";
    self.tls = false;
    self.allowUntrustedCertificates = false;
    self.pinnedCertificates = nil;
    return self;
}

- (void)open {
    DDLogVerbose(@"[MQTTWebsocketTransport] open");
    self.state = MQTTTransportOpening;
    
    NSURL *url = [NSURL URLWithString: self.url];
    NSMutableURLRequest *urlRequest = [NSMutableURLRequest requestWithURL:url];

    urlRequest.SR_SSLPinnedCertificates = self.pinnedCertificates;
    NSArray <NSString *> *protocols = @[@"mqtt"];
    
    self.websocket = [[SRWebSocket alloc] initWithURLRequest:urlRequest
                                                   protocols:protocols
                              allowsUntrustedSSLCertificates:self.allowUntrustedCertificates];
    
    self.websocket.delegate = self;
    [self.websocket open];
}

//- (NSURL*) endpointURL {
//    NSString *protocol = (self.tls) ? @"wss" : @"ws";
//    NSString *portString = (self.port == 0) ? @"" : [NSString stringWithFormat:@":%d",(unsigned int)self.port];
//    NSString *path = self.path;
//    NSString *urlString = [NSString stringWithFormat:@"%@://%@%@%@",
//                           protocol,
//                           self.host,
//                           portString,
//                           path];
//    NSURL *url = [NSURL URLWithString:urlString];
//    return url;
//}

```

In short I stopped using `endpointURL` method. 

How to use this now: 

```
var session = MQTTSession()
session.delegate = self
        
let wsTransport = MQTTWebsocketTransport()
wsTransport.url = url
        
session.transport = wsTransport
session.clientId = self.deviceId
session.connect()

```

**Comment by jcavar** [comment]
@mendirattanishant could you create a PR? Instead of commenting out code, I think we just need to check if url is set, otherwise logic stays the same.

**Comment by nmendiratta** [comment]
@jcavar  Yes, I am working on creating a PR for this.

**Comment by jcavar** [comment]
Nice, thank you!

**Comment by mendirattanishant** [comment]
@yusufonderd 
Can you check if you signed URL contains "/mqtt" path in it?

**Comment by yusufonderd** [comment]
Yes my url is signed url and contains '/mqtt' path. I successfully connecting android side with same url.

**Comment by mendirattanishant** [comment]
@jcavar  Can you provide guidelines on how to build the project on XCode with my changes?

**Comment by yusufonderd** [comment]
There is no problem about your changes. I successfully applied your changes on my project.

**Comment by yusufonderd** [comment]
I've been working on the same problem for two weeks. Do you have any idea ?

**Comment by jcavar** [comment]
It is hard to say without more info, if you could debug and find more details then it might be more clear.

**Comment by nmendiratta** [comment]
@yusufonderd  It worked for me after I provided my own url. Please provide more logs for a better clarity.

**Comment by mendirattanishant** [comment]
@yusufonderd  I use the same pre signed url like 
`wss://axxxxxxxx.iot.us-east-1.amazonaws.com/mqtt?` 
with parameters as credentials, etc. In PR #461 I addressed how we can make sue of this library to inject our custom pre signed url and it works for me. Can you please try again?

**Comment by yusufonderd** [comment]
Hi @mendirattanishant  thank you for your patient. Now I successfully connected websocket. But I cannot subscribe topic :) When i sucscribe a topic, I cannot receive any callback.

```
session?.subscribe(toTopic: subscriptionTopic, at: MQTTQosLevel.exactlyOnce, subscribeHandler: { (err, gQoss) in
                            if (err != nil){
                                print("MQTTSessionx Subscription failed \(err)");
                            }else{
                                print("MQTTSessionx Subscription sucessfull! Granted Qos: \(gQoss)");
                            }
                        })

```

**Comment by nmendiratta** [comment]
@yusufonderd please check if your url is correct.

```
wsTransport.url = NSURL(string: url) as! URL
session.transport = wsTransport
```

**Comment by mendirattanishant** [comment]
@yusufonderd  please check if your url is correct.

```
wsTransport.url = NSURL(string: url) as! URL
session.transport = wsTransport
```

**Comment by jcavar** [comment]
I will close this issue now, we now have support for custom URL. Please open separate issue if you still have it with specific details about it.
