### ISSUE TITLE
unable to create separate connections while running  multiple Vusers in loadrunner

### ISSUE THREAD

**Issue by yshnr1010** [novastone-media/MQTT-Client-Framework#434]
we are unable to create multiple connections for multiple VUSERS running in controller .
we are seeing the below error:
 "Server closed the connection. Probably, another client with Client ID 'mimic2/mqtt/#' has just connected, or the server doesn't support the passed parameters."

see my LR script below and suggest any changes needed

vuser_init()
{
    lr_start_transaction("login");

    /* Declared in "globals.h" */
    client = mqtt_create();
    
    
    mqtt_set_client_id(client, "mimic2/mqtt/#");
    
    //mqtt_set_credentials(client, "<guest>", "<12345>");
    mqtt_set_lwt(client, "BCDS/#", "<sample lwt payload>", MQTT_AUTO, MQTT_DEFAULT, MQTT_RETAIN);
    
    
    /* Connect to an MQTT broker */
    mqtt_connect(client, "tcp://iot.eclipse.org");
    
    /* Uncomment the following if implementing the "subscriber" logic */
    mqtt_subscribe(client, "BCDS/#");
    
    lr_end_transaction("login", LR_AUTO);

    
    return 0; 

please anyone see on this issue and reply to my mail "vayhehaar@gmail.com"

**Comment by jcavar** [comment]
You are not allowed to create multiple connections from client with same id.

**Comment by yshnr1010** [comment]
we have changed the cliend ID's and tried... it was successfully running in VUGEN.
but when we add more than one VUSERS in controller and run ,then first vuser gets disconnected and second user gets connected and the disconnected VUSER will be appearing under failed section..

**Comment by jcavar** [comment]
Are those users using same client id?

**Comment by yshnr1010** [comment]
yes, they are using the same client ID ..
how can we make Vuser use the Different CLient ID specified in the script below:

   
vuser_init()
{
    lr_start_transaction("login");

    /* Declared in "globals.h" */
    client1 = mqtt_create();
    client2 = mqtt_create();
        
    mqtt_set_client_id(client1, "mimic2/mqtt/1");
    mqtt_set_client_id(client2, "mimic2/mqtt/2");
    // mqtt_set_credentials(client, "<username placeholder>", "<password placeholder>");
    mqtt_set_lwt(client1, "BCDS/#", "<sample lwt payload>", MQTT_AUTO, MQTT_DEFAULT, MQTT_RETAIN);
    mqtt_set_lwt(client2, "BCDS/#", "<sample lwt payload>", MQTT_AUTO, MQTT_DEFAULT, MQTT_RETAIN); 

/* Connect to an MQTT broker */
    mqtt_connect(client1, "tcp://iot.eclipse.org");
    mqtt_connect(client2, "tcp://iot.eclipse.org");
    
    /* Uncomment the following if implementing the "subscriber" logic */
    mqtt_subscribe(client1, "BCDS/#");
    mqtt_subscribe(client2, "BCDS/#");
    
    lr_end_transaction("login", LR_AUTO);
    return 0;
}

**Comment by jcavar** [comment]
I am not familiar with your framework but I assume you need to invoke vuser_init with different client id.

**Comment by yshnr1010** [comment]
with which framework are you familiar..
and how would you use two or more VUSERS and run the script

**Comment by jcavar** [comment]
Are you using MQTT-Client-Framework? Because from your code it seems like it is something else.

**Comment by yshnr1010** [comment]
yeah MQTT..
we are using GAMBIT  simulator and hiveMQ as broker

**Comment by jcavar** [comment]
Yeah so not this client framework. I am not familiar with GAMBIT or hiveMQ either.

**Comment by yshnr1010** [comment]
can you suggest which simulator and broker will be best for the IOT performance testing

**Comment by jcavar** [comment]
I can't unfortunately. I have no experience with IOT.

**Comment by yshnr1010** [comment]
thanks for the help
