### ISSUE TITLE
Incoming messages are slow

### ISSUE THREAD

**Issue by romuye123** [novastone-media/MQTT-Client-Framework#436]
Hi @ckrey @jcavar 
I am using Objective-C client. Here is how I connect

```
    transport = [[MQTTCFSocketTransport alloc] init];
    transport.host = MQTT_HOST_NAME;
    transport.port = MQTT_HOST_PORT;
    session = [[MQTTSession alloc] init];
    session.transport = transport;
    session.delegate = self;
    session.userName = MQTT_USERNAME;
    session.password = MQTT_PASSWORD;
    [session connectAndWaitTimeout:5];

```

The incoming message are slow as compared to Android Paho client.
`- (void) newMessage:(MQTTSession *)session data:(NSData *)data onTopic:(NSString *)topic qos:(MQTTQosLevel)qos retained:(BOOL)retained mid:(unsigned int)mid
`

Publish works perfectly fine and is super quick.
` [session publishData:[payload dataUsingEncoding:NSUTF8StringEncoding] onTopic:topicName retain:NO qos:MQTTQosLevelAtLeastOnce];`

Please suggest if I am doing anything wrong. Looking forward for your reply.

Thanks

**Comment by ckrey** [comment]
Cam you add a bit of objective figures, please!
QoS? Size of messages? Number of messages in a burst? Number messages received per second?

**Comment by romuye123** [comment]
QOS: 1
Size of messages: 99 ( characters ) or data.length also prints 99
Number of messages in a burst: 1 or 2 max
Number messages received per second: 1 or 2 max


**NOTE:**
When i connect my iOS client to my phone's 4G cellular network, there is no delay in incoming message. 
I am connecting via broadband router at home and at the exact same time messages to my hardware device as well as my android phone work absolutely fine, just the delay in iOS client.

**Comment by romuye123** [comment]
Hi @ckrey,

Any update on this issue ?
Randomly this issue disappears and appears again.

Looking forward for your reply.

**Comment by jcavar** [comment]
Maybe related to https://github.com/novastone-media/MQTT-Client-Framework/issues/395

**Comment by jcavar** [comment]
@romuye123 have you been able to resolve this issue?

Does it happen on simulator?
If you could write automated test with your scenario in our test suite, it should be easier to debug your issue.

**Comment by romuye123** [comment]
@jcavar this happened to be a router related issue for me, i changed my WiFi router and it worked, but i am still not convinced with it, how come it works on Android ? and it even works perfect when i switch to 3G/4G connection on my cellphone.

**Comment by jcavar** [comment]
I guess it might be related to network stack differences between iOS and Android, but yeah, it is weird.

Are you ok to close this issue?

**Comment by romuye123** [comment]
Sure i am happy to close this issue, will report if I find anything interesting related to the issue.

**Comment by jcavar** [comment]
Nice, thanks.
