### ISSUE TITLE
Some imports are missing for MQTTClient's umbrella header

### ISSUE THREAD

**Issue by olbartek** [novastone-media/MQTT-Client-Framework#440]
Xcode says that umbrella header for module `MQTTClient` does not include some headers. 
I am attaching screenshot with the issue.

<img width="413" alt="screen shot 2018-03-23 at 21 35 09" src="https://user-images.githubusercontent.com/2855862/37852485-0b59e15e-2ee3-11e8-8401-1cb80e84c55e.png">

The issue occurred to me in a Swift project and it does not occur every time. I've noticed that when you clean derived data it is more likely to happen.

**Comment by jcavar** [comment]
Thank you for reporting this. Some of those classes are private and are not imagined to be exposed to outside so I am not sure if we should add them? I would like to fix warnings you are getting though. Do you know any other way to silence warning without including those files?

**Comment by mciuba** [comment]
Maybe the problem is caused by all these headers being set as "public" in "Target Membership"? As described in this answer: https://stackoverflow.com/a/38740111/2128900
Setting the headers which shouldn't be exposed to the outside to "private" in "Target Membership" could fix the issue

**Comment by jcavar** [comment]
That makes sense. If someone wants to give it a try it would be nice, otherwise I will do it when I find some time.

**Comment by kprofic** [comment]
I have just sent a PR this does exactly this: some headers are moved to "project" instead of "public"

**Comment by jcavar** [comment]
Ok, 0.13.1 is out now. Please give it a try.

**Comment by kprofic** [comment]
Seems to work fine now, thanks!
