### ISSUE TITLE
Connection Closed by broker

### ISSUE THREAD

**Issue by vipulsinghania** [novastone-media/MQTT-Client-Framework#447]
Hi Below is my code for establishing mqtt connection over websocket.
For code below i am getting  Connection Closed by broker and then connection is closed.
Kindly help.

    var sessionManager = MQTTSessionManager()
    var serieID:Int = 265

   sessionManager.connect(to: "apidev.cloudtimer.nl",
                  port: 1883,
                  tls:  false,
                  keepalive: 60,
                  clean: true,
                  auth: false,
                  user: nil,
                  pass: nil,
                  will: false,
                  willTopic: nil,
                  willMsg: nil,
                  willQos: .atMostOnce,
                  willRetainFlag: true,
                  withClientId: nil
        )
        sessionManager.delegate = self
        sessionManager.session.protocolLevel = .version311
        sessionManager.session.delegate = self

         let channel = String(format:"serie_%d",self.serieID)
         sessionManager.session.subscribe(toTopic: channel, at: .atLeastOnce)

**Comment by jcavar** [comment]
Unfortunately websocket transport is not supported for `MQTTSessionManager`. You will need to manually use `MQTTSession` and set transport property to instance of `MQTTWebsocketTransport`.
