### ISSUE TITLE
Make MQTTLog.h public

### ISSUE THREAD

**Issue by benstadin** [novastone-media/MQTT-Client-Framework#450]
Hi,

I found the default verbose logging for debug builds to be quite annoying while debugging my own application (lots of verbose MQTT log messages in between of what I was looking for). Though changing the log is not possible without the header for MQTTLog.h being public.

Thanks
Ben

**Comment by jcavar** [comment]
That sounds like a good idea, we would be happy to accept PR with that.

**Comment by jcavar** [comment]
This is now done. You can find it in 0.15.0 release.
