### ISSUE TITLE
MqttsessionManager connection not working.

### ISSUE THREAD

**Issue by manju-ms** [novastone-media/MQTT-Client-Framework#452]
I am using MQTTSessionManager, After calling connectTo Method, The newState value will be 0 initial and it will beacome 1 after 5 seconds and stops there. It is not throwing any error also. Here is my connect method.

[self.manager connectTo:host
                                       port :port
                                       tls:60
                                      keepalive:true
                                     clean:true
                                     auth:true
                                      user:username
                                     pass:password
                                    willTopic:nil
                                   will:nil
                                   willQos:MQTTQosLevelAtMostOnce
                                   willRetainFlag: yes
                                   withClientId:@"id"]

The didChangeState method will return initial 0 and then 1 and stops. Is i am missing any configuration?

**Comment by jcavar** [comment]
It is hard to say from info that you posted. It would be good if you could debug and provide more info about what is happening.

**Comment by jcavar** [comment]
I will close due to inactivity, feel free to reopen with more info if you still have this issue.
