### ISSUE TITLE
cError:Optional(Error Domain=kCFErrorDomainCFNetwork Code=1 "(null)" UserInfo={_kCFStreamErrorCodeKey=1, _kCFStreamErrorDomainKey=12})

### ISSUE THREAD

**Issue by yusufonderd** [novastone-media/MQTT-Client-Framework#458]
I'm trying to connect aws signed url.  
   ```
let webSocketUrl = "a2xxxxxxxx.iot.us-east-1.amazonaws.com/mqtt?..."
   var  transport = MQTTCFSocketTransport()
   transport.host = webSocketUrl
   transport.port = 443;
    let session = MQTTSession()
    session?.transport = transport;
    session?.connect(connectHandler: { (error) in
           print("error:\(error)")
    })                

```
I give an exception : 

cError:Optional(Error Domain=kCFErrorDomainCFNetwork Code=1 "(null)" UserInfo={_kCFStreamErrorCodeKey=1, _kCFStreamErrorDomainKey=12})

**Comment by NathanMrtns** [comment]
Try this:        

```  let transport: MQTTWebsocketTransport = MQTTWebsocketTransport()
        transport.host = "a2xxxxxxxx.iot.us-east-1.amazonaws.com"
        transport.path = "/mqtt?..."
        transport.port = 443
        transport.tls = true
        session.transport = transport
        session.userName = "your-username"
        session.password = "your-password"
        session.protocolLevel = .version311
        session.clientId = String(ProcessInfo().processIdentifier)
        session.connect()```

**Comment by yusufonderd** [comment]
MQTTCFSocketTransport object has not  'path' properties.

**Comment by NathanMrtns** [comment]
@yusufonderd updated the answer with the right transport

**Comment by yusufonderd** [comment]
@NathanMrtns  Now I'm getting two different error when change tls value : 

When `transport.tls = true` :  Error Domain=SRWebSocketErrorDomain Code=2132 "received bad response code from server 403" UserInfo={NSLocalizedDescription=received bad response code from server 403, HTTPResponseStatusCode=403}

When `transport.tls = false`  : Error Domain=MQTT Code=-8 "Server has closed connection without connack." UserInfo={NSLocalizedDescription=Server has closed connection without connack.}

**Comment by NathanMrtns** [comment]
@yusufonderd do you need a certificate to connect?

**Comment by yusufonderd** [comment]
No I'm using generated URL. This url already authorized.

**Comment by jcavar** [comment]
Hi @yusufonderd. As @NathanMrtns pointed, please check https://github.com/novastone-media/MQTT-Client-Framework/issues/433 to work with signed url. You will need to subclass `MQTTWebsocketTransport`

**Comment by jcavar** [comment]
Tracked in #433
