### ISSUE TITLE
How do I adapt this code to maintain the connection in background?

### ISSUE THREAD

**Issue by NathanMrtns** [novastone-media/MQTT-Client-Framework#469]
Hi, every time the app goes to background the connection closes. I've seen some codes here that is possible to maintain the connection but I don't know how to adapt. Any help?
```
        let session = MQTTSession()
        let transport: MQTTWebsocketTransport = MQTTWebsocketTransport()
        transport.host = "host address"
        transport.path = "/mqtt"
        transport.port = port
        transport.tls = true
        session.transport = transport
        session.userName = "username"
        session.password = "pass"
        session.protocolLevel = .version311
        session.clientId = String(ProcessInfo().processIdentifier)
        session.connect()
```

**Comment by jcavar** [comment]
Just don't disconnect and start background task:

https://developer.apple.com/documentation/uikit/uiapplication/1623031-beginbackgroundtask

This will work for short running tasks, for long running your app needs to be in category of apps that are allowed to exectute long running background task, e.g voip

**Comment by NathanMrtns** [comment]
@jcavar What about the MQTTSessionManager with the connectInForeground flag?

**Comment by jcavar** [comment]
That is I think opposite of what you want. `MQTTSessionManager` can handle reconnection when coming from background, but you don't want to disconnect when you go to background?

**Comment by NathanMrtns** [comment]
@jcavar I see. Yeah, I want to keep the connection if the app goes to background.

**Comment by NathanMrtns** [comment]
The connection was closing when I blocked the device. I just made an observer that is notified everytime the application goes foreground and the session is not connected. This resolved my problem, but any other suggestion is welcome :)
