### ISSUE TITLE
The other party also logged in to my account. Why am I still reconnecting here? Shouldn't I be offline?

### ISSUE THREAD

**Issue by 964562398** [novastone-media/MQTT-Client-Framework#470]
For example, A sets the clientId to 1 and then connects. B also sets the clientId to 1 and then connects. According to reason, A should go offline instead of trying to reconnect. A getting to MQTTSessionEventConnectionClosedByBroker will always call the triggerDelayedReconnect method. How to get offline status.

对方也登录了我的账号，我这边为什么还会一直重新连接，不是应该我这边下线吗？

比如A设置了clientId 为1然后连接，B也设置了clientId 为1然后连接，按道理A应该下线，而不是一直尝试重连，A获取到MQTTSessionEventConnectionClosedByBroker一直会去调用triggerDelayedReconnect方法。请问如何获取下线状态。

**Comment by jcavar** [comment]
Are you using `MQTTSessionManager`? The idea of it is to provide automatic reconnection. If you don't need that, you can use `MQTTSession` directly.

**Comment by 964562398** [comment]
@jcavar ok Thanks
