### ISSUE TITLE
MQTTSession subscribeToTopics:subscribeHandler: crashing with EXC_BAD_ACCESS KERN_INVALID_ADDRESS bug When the APP starts 

### ISSUE THREAD

**Issue by xuchengcheng** [novastone-media/MQTT-Client-Framework#472]
Crashed: com.tuya.kTPMqttSubscribeServiceQueueName
0  libobjc.A.dylib                0x1d494dc6 objc_msgSend + 5
1  TuyaSmartPublic                0x3789b9 -[MQTTSession subscribeToTopics:subscribeHandler:] (MQTTSession.m:182)
2  TuyaSmartPublic                0x3787d5 -[MQTTSession subscribeToTopic:atLevel:subscribeHandler:] (MQTTSession.m:162)
3  TuyaSmartPublic                0xd803bb __32-[MqttService subscribeToTopic:]_block_invoke (MqttService.m:275)
4  libdispatch.dylib              0x1d8cd797 _dispatch_call_block_and_release + 10
5  libdispatch.dylib              0x1d8da59d _dispatch_queue_serial_drain + 854
6  libdispatch.dylib              0x1d8d0b71 _dispatch_queue_invoke + 886
7  libdispatch.dylib              0x1d8daa1f _dispatch_queue_override_invoke + 282
8  libdispatch.dylib              0x1d8dc1b5 _dispatch_root_queue_drain + 326
9  libdispatch.dylib              0x1d8dc00f _dispatch_worker_thread3 + 106
10 libsystem_pthread.dylib        0x1da8287d _pthread_wqthread + 1040
11 libsystem_pthread.dylib        0x1da8245c start_wqthread + 8

**Comment by jcavar** [comment]
Would it be possible to add test case for this? Or investigate more in detail what might cause it?

**Comment by jcavar** [comment]
Closing because there was not activity. Feel free to reopen with more info.
