### ISSUE TITLE
Disconnect when app has been in the background for some time.

### ISSUE THREAD

**Issue by MagLiC** [novastone-media/MQTT-Client-Framework#473]
I have set connectInForeground is NO. But when app has been in the background for about 3 minutes, it disconnects without any callback. Log of checkDup also doesn't print. 
App isn't killed and when it enters foreground, it reconnect and the log of checkDup starts print.

**Comment by jcavar** [comment]
You are probably reaching iOS limit of background execution and iOS suspends your app.

**Comment by jcavar** [comment]
I will close this issue due to inactivity, feel free to reopen with more info.
