### ISSUE TITLE
Framework unable to connect ActiveMQ server hosted in AWS

### ISSUE THREAD

**Issue by ankitsamal** [novastone-media/MQTT-Client-Framework#477]
I have been trying to connect to my MQTT server hosted in AWS but the connection closes all the time

self.manager = [[MQTTSessionManager alloc] init];
    self.manager.delegate = self;
    
    self.manager.subscriptions = [NSDictionary dictionaryWithObject:[NSNumber numberWithInt:MQTTQosLevelExactlyOnce]
                                                             forKey:[NSString stringWithFormat:@"%@", @"try1Mqtt"]];
    
    [self.manager connectTo:@"b-******************.mq.us-east-1.amazonaws.com" port:8883 tls:FALSE keepalive:60 clean:true auth:TRUE user:@"********" pass:@"******" will:[@"offline" dataUsingEncoding:NSUTF8StringEncoding] willTopic:[NSString stringWithFormat:@"%@",
                                                                                                                                                                                                    @"try1Mqtt"]
                    willMsg:nil willQos:MQTTQosLevelExactlyOnce willRetainFlag:FALSE withClientId:@"asamal" securityPolicy:nil certificates:nil protocolLevel:4 connectHandler:^(NSError *error) {
                        
                        if (error) {
                            NSLog(@"Subscription failed %@", error.localizedDescription);
                        } else {
                            NSLog(@"Subscription sucessfull! Granted Qos: %@", error);
                        }
                        
                        
                    }];

**Comment by jcavar** [comment]
Can you please add more info, how it fails, logs.

**Comment by jcavar** [comment]
Ok there is same issue I see now. I will close this one in favour of:
https://github.com/novastone-media/MQTT-Client-Framework/issues/476
