### ISSUE TITLE
Frequent disconnect problem

### ISSUE THREAD

**Issue by ashish-gupta-bs** [novastone-media/MQTT-Client-Framework#478]
- [ ] How can I set "serverKeepAlive" to zero while connecting to the server as it's the read only property ? Here is my code - 

        let scTransport = MQTTWebsocketTransport.init()
        scTransport.host = "example.com"
        scTransport.tls = true
        scTransport.port = 0
        
        session?.userName = "username"
        session?.delegate = self
        session?.transport = scTransport
        session?.connect()

**Comment by jcavar** [comment]
`serverKeepAlive` is server setting, you can change `keepAliveInterval` on `MQTSession`

**Comment by jcavar** [comment]
Closing because there was not activity. Feel free to reopen with more info.
