### ISSUE TITLE
Project real war problem

### ISSUE THREAD

**Issue by zhangtong217** [novastone-media/MQTT-Client-Framework#485]
I use this framework in the project, we use ClientID as an account system, when the account changes equipment, two cell phone ends will fall into the dead cycle。 Android squeezed out and has Specific error code  ；but us ， has a equal closed state when i has been squeezed back, our side exit backstage, broken net,  what should I do？ 

就是安卓端被挤掉会有一个特定的状态，表示当前clientid 被挤掉了，，，我们这边断网、被挤掉、退出后台 都是 closed状态，导致更换设备clientid作为账户体系不好使，能改进吗？

**Comment by jcavar** [comment]
Sorry @zhangtong217, I think I don't understand your issue, can you please explain in more detail?

**Comment by jcavar** [comment]
Closing because there was not activity. Feel free to reopen with more info.
