### ISSUE TITLE
Unsubscribe to all subscribed topics

### ISSUE THREAD

**Issue by NathanMrtns** [novastone-media/MQTT-Client-Framework#486]
- Be able to unsubscribe from all subscribed topics
I've been looking at the source code and I can't find this option. I believe it would be a good feature to add.

- Be able to unsubscribe from all subscribed topics with a particular URL slice. 
For example, if a topic is: "mainTopic/realTime/{id}", add a feature to be able to unsubscribe topics containing the string "mainTopic/realTime"

I could help to implement those too, I just need a direction.

**Comment by NathanMrtns** [comment]
I didn't know about that. But it doesn't seem to work here.
My topics are like "level1/{someDeviceID}/level3/level4" then I tried to unsubscribe "level1/#" and "level1/+/level3/level4" and it didn't work.

**Comment by jcavar** [comment]
It didn't work in which way? Did you get unsubscribed from any?

**Comment by NathanMrtns** [comment]
No, I still received messages from the subscribed topic

**Comment by jcavar** [comment]
But what happens on unsubscribe, do you get error?

**Comment by NathanMrtns** [comment]
unsubackReceived is called but I still receive messages after that. No errors

**Comment by jcavar** [comment]
Which broker are you using?

**Comment by NathanMrtns** [comment]
Some outside broker that I dont know the implementation of. I beleive their implementation dont allow widcards?

**Comment by jcavar** [comment]
Hmm, could be, are you able to verify that with them somehow?

**Comment by NathanMrtns** [comment]
I'll try. Talk here if they give me any feedback.

**Comment by NathanMrtns** [comment]
Hey @jcavar 
I was testing here with MQTT Box and Wildcards are working on the broker server (I believe is automatic). But I believe [this explanation](https://groups.google.com/forum/#!topic/mqtt/eWf46f6d1wU) answers my doubt. 

When Tobias says:

> 2)
> Client subscribes "finance/stock/ibm/closingprice" and
> unsubscribes "finance/stock/ibm/#"
> 
> The unsubscribe for "finance/stock/ibm/#" is silenty
> ignored (was never subscribed on that very "topic subsc. string")
> 
> It will still receive msgs for "finance/stock/ibm/closingprice"
> since it is still subscribed to "finance/stock/ibm/closingprice"

If this is right, this could be a implemented feature here?

**Comment by jcavar** [comment]
Interesting, yes it does seem like documentation specifies that in [3.10.4 section](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718072)

**Comment by jcavar** [comment]
Are you using `MQTTSessionManager` maybe? It maintains list of subscriptions and it is easy to unsubscribe from all sessions by setting that property.

I think it makes  sense to add it to `MQTTSession` as well I am just not sure in which form and would like to clean it up first before adding new features.

**Comment by NathanMrtns** [comment]
Hey @jcavar It's been a while since I coded that. I believe I tried to use MQTTSessionManager but it didn't work, I'm not sure. I, somehow, did a workaround but I don't remember how. 

I can close the issue, though.

**Comment by jcavar** [comment]
Thanks @NathanMrtns, lets then close for now.
