### ISSUE TITLE
Problem for using library in React-Native at NSRunLoop

### ISSUE THREAD

**Issue by Husseinhj** [novastone-media/MQTT-Client-Framework#488]
I use the **old version** of the library in my framework. (version 0.3.x)
When I want to create a _React-Native_ bridge for my framework and find out could not connect to the broker and after reviewing **MQTT** library, Find out the problem is `[NSRunLoop currentRunLoop]` for instantiating `MQTTSession`.

When change `runLoop` parameter of `MQTTSession` constructor to `[NSRunLoop mainRunLoop]` my problem solved. But I don't know Is it best practice or it could have some breaking change on my framework?

```objective-c
[[MQTTSession alloc] initWithClientId:self.brokerClientId
                                                        userName:self.username
                                                        password:self.password
                                                       keepAlive:180.0f
                                                    cleanSession:false
                                                         runLoop:[NSRunLoop mainRunLoop]
                                                         forMode:NSDefaultRunLoopMode];
```

**Comment by jcavar** [comment]
Is there a reason that you need to use old version of library? If not I would suggest to switch to new and use dispatch queues.

Your problem was probably that run loop finished and you would not be able to connect. 

Your approach with `[NSRunLoop mainRunLoop]` will work on main thread. That is sometimes ok, sometimes not, depends on your use case.

**Comment by Husseinhj** [comment]
> Is there a reason that you need to use old version of library?

Yes, it could have some breaking change in our framework so we are not ready to upgrade **MQTT** library for now.

> Your approach with [NSRunLoop mainRunLoop] will work on main thread. That is sometimes ok, sometimes not, depends on your use case.

In my use case, It's work for me.
