### ISSUE TITLE
delay disconnection when app is terminating

### ISSUE THREAD

**Issue by hang321** [novastone-media/MQTT-Client-Framework#489]
May I ask is it possible to delay the MQTT disconnection when app is terminating? I am using `MQTTSessionManager` and wondering how to modify `disconnectWithDisconnectHandler` or something else.

What I actually want to implement is sending a message to server when `applicationWillTerminate` is invoked. According to Apple doc, there is about 5 seconds to finish tasks before app terminated.

It is similar to issues #399, yet only stay connected for few seconds.

**Comment by jcavar** [comment]
Can you use MQTT `will` message?

**Comment by hang321** [comment]
thanks jcavar. 
The requirement includes location when application terminated. Using `Will` message requires constantly update the Last Will and Testament(LWT), which may not fit in this situation.

So far, I found out the MQTT broker logged disconnection once app is in the background, before app terminated. it is called in `ForegroundReconnection`.`appWillResignActive`. I will try to add an observer for `UIApplicationWillTerminateNotification` there to see what will happen.

**Comment by hang321** [comment]
Adding observer for `UIApplicationWillTerminateNotification` with reconnect > sleep 3 seconds > disconnect. Mqtt connection status only go to `MQTTSessionManagerStateConnecting` yet never reach `MQTTSessionManagerStateConnected`.

At the end we changed our use case and no longer go for sending app terminate message immediately. Thanks for your time.
