### ISSUE TITLE
[MQTTWebsocketTransport setUrl:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by stellz** [novastone-media/MQTT-Client-Framework#492]
Few minutes ago I updated my pods using "pod update" and noticed that MQTTClient updated.

> Installing MQTTClient 0.15.0 (was 0.14.0 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)

After running my project I  immediately received a crash: 

> [MQTTWebsocketTransport setUrl:]: unrecognized selector sent to instance
> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MQTTWebsocketTransport setUrl:]: unrecognized selector sent to instance

**Comment by jcavar** [comment]
Did you have version from master before?
Could you paste diff produced by `pod update`?

**Comment by sudhamoorthi** [comment]
Hi, i am also facing the same issue. How do you resolve this issue?

**Comment by stellz** [comment]
@jcavar Unfortunately I can't paste the diffs, but yes, I think the previous version was from the master branch. I joined the project that I'm working on recently and don't have much info about the initial start. 

@sudhamoorthi I just changed the version to the previous one editing the Podfile 

> pod 'MQTTClient', '0.14.0'

**Comment by jcavar** [comment]
That is weird. Can you try changing

https://github.com/novastone-media/MQTT-Client-Framework/blob/master/MQTTClient/MQTTClient/MQTTWebsocketTransport/MQTTWebsocketTransport.m#L22

from `@dynamic` to `@sythesize`

locally in your pod?

**Comment by jcavar** [comment]
This is now resolved in 0.15.1 release, please update your pods. Thanks for reporting!
