### ISSUE TITLE
Connectivity Issue after updating

### ISSUE THREAD

**Issue by RajaReddyiOS** [novastone-media/MQTT-Client-Framework#494]
i don't know what exactly happening with my connectivity and my Mqtt broker was not connecting to the client. I was wondering even there was no errors and warnings and there was a couple of issues also opened by other which was related to my issue.

I hope i'll get reply and i wish u people fix this issue ASAP or is it my bad the way i approach 

self.sessionManager?.connect(to: host, port: port, tls: true, keepalive: 240, clean: true, auth: true, user: self.userName, pass: self.password, will: true, willTopic: connectivityTopic, willMsg: message, willQos: MQTTQosLevel.atMostOnce, willRetainFlag: true, withClientId: self.userName, securityPolicy: nil, certificates: nil, protocolLevel: MQTTProtocolVersion.version311, connectHandler: { (error) in
    print(error  , "mqtt error")
})

Thank you

**Comment by hang321** [comment]
Remove deprecated APIs https://github.com/novastone-media/MQTT-Client-Framework/commit/1c54ada3dbd431e6da1b840b0214efae12768b82
looks like `connectToHost` is removed, `MQTTSessionManager.m` does not attempt to connect at all. Status remains connecting.

**Comment by mixo44** [comment]
I found that you have removed part of transport initialization.
```
MQTTCFSocketTransport *transport;
   if (self.securityPolicy) {
       transport = [[MQTTSSLSecurityPolicyTransport alloc] init];
       ((MQTTSSLSecurityPolicyTransport *)transport).securityPolicy = self.securityPolicy;
   } else {
       transport = [[MQTTCFSocketTransport alloc] init];
   }
   transport.host = host;
   transport.port = port;
   transport.tls = usingSSL;
   transport.certificates = self.certificates;
   transport.voip = self.voip;
   transport.queue = self.queue;
   transport.streamSSLLevel = self.streamSSLLevel;
   self.transport = transport;
```
So when the session tries to call `open` the transport is `nil`. 
[Code line](https://github.com/novastone-media/MQTT-Client-Framework/blob/8181373ae6bad104caa32e309ee57f4807b1bc09/MQTTClient/MQTTClient/MQTTSession.m#L1553)

**Comment by ezisxl** [comment]
the same - had to lock pod to 0.14.0 . :/

**Comment by jcavar** [comment]
Sorry guys, I did remove some old deprecated APIs, but I am still not sure what is broken. In our project everything is working fine. Could someone investigate problem and report findings back so we can work it out.

**Comment by ezisxl** [comment]
in short I was doing just
```
self.manager = [[TTMQTTSessionManager alloc] initWithQueue:self.mqttQueue];
self.manager.delegate = self;
[self.manager connectTo:
..
		connectHandler:^(NSError *error)
		{
		 ..
		 }
];
```
so that stopped working :D

**Comment by jcavar** [comment]
Could you try latest version from master?

**Comment by ezisxl** [comment]
the same
basically my setup is +- like

```
self.manager = [[MQTTSessionManager alloc] initWithQueue:self.mqttQueue];
self.manager.delegate = self;

[self.manager connectTo:hostname
                   port:port
                    tls:YES
              keepalive:keepaliveInterval
                  clean:YES
                   auth:YES
                   user:user
                   pass:password
                   will:NO
              willTopic:nil
                willMsg:nil
                willQos:MQTTQosLevelExactlyOnce
         willRetainFlag:NO
           withClientId:clientId
         securityPolicy:nil
           certificates:nil
          protocolLevel:MQTTProtocolVersion311
         connectHandler:^(NSError *error)
 {
     if (error)
     {
         //error codes list https://gist.github.com/nelsonsar/549f7167aa2091afafa5
         DDLogError(@"Mqqt error connecting:\n%@",error);
         [self didConnectSuccessfully:NO];
     }
 }];

[self.manager addObserver:self
               forKeyPath:@"state"
                  options:NSKeyValueObservingOptionInitial | NSKeyValueObservingOptionNew
                  context:nil];
				  
- (void)observeValueForKeyPath:(NSString *)keyPath
                      ofObject:(id)object
                        change:(NSDictionary *)change
                       context:(void *)context
{
    switch (self.manager.state)
    {
	..
}

```

this used to work before 0.15

**Comment by jcavar** [comment]
Latest code from master doesn't work for you?

**Comment by ezisxl** [comment]
jup - just now tried with latest master
seems like I can ditch my sessionManager, create session and transport manually - then it works.

**Comment by ezisxl** [comment]
also I'm getting constants "**resend PUBLISH** .." it sending out (repeating) random old messages

**Comment by jcavar** [comment]
@ezisxl so you tried with this change in https://github.com/novastone-media/MQTT-Client-Framework/commit/33e06af6ae0c5d93f51191fdd0c2d8453c5ddfa9 and it still doesn't work?

Sorry for asking third time, just need to understand the problem we have here.

**Comment by ezisxl** [comment]
I thought I did, just downloaded the zip.. but now I pulled and it is working! thx! sorry for trouble :)

I still get those **resend PUBLISH** though :/

**Comment by jcavar** [comment]
There is 0.15.2 release now. Please try it out.

@ezisxl please open new issue for resend PUBLISH problem, it doesn't seem related to this.
