### ISSUE TITLE
MQTTSessionManager "self.session.transport is nil" Probrem on latest version 0.15.1

### ISSUE THREAD

**Issue by ericXjj** [novastone-media/MQTT-Client-Framework#498]
On MQTTSessionManager , I have the same problem like : [494#issuecomment-418124409](https://github.com/novastone-media/MQTT-Client-Framework/issues/494#issuecomment-418124409) , but I found it is solved in MQTTSessionManager "- (void)connectToInternal:(MQTTConnectHandler)connectHandler" at https://github.com/. like below:
`- (void)connectToInternal:(MQTTConnectHandler)connectHandler {
    if (self.session && self.state == MQTTSessionManagerStateStarting) {
        [self updateState:MQTTSessionManagerStateConnecting];
        MQTTCFSocketTransport *transport;
        if (self.securityPolicy) {
            transport = [[MQTTSSLSecurityPolicyTransport alloc] init];
            ((MQTTSSLSecurityPolicyTransport *)transport).securityPolicy = self.securityPolicy;
        } else {
            transport = [[MQTTCFSocketTransport alloc] init];
        }
        transport.host = self.host;
        transport.port = self.port;
        transport.tls = self.tls;
        transport.certificates = self.certificates;
        transport.voip = self.session.voip;
        transport.queue = self.queue;
        transport.streamSSLLevel = self.streamSSLLevel;
        self.session.transport = transport;
        [self.session connectWithConnectHandler:connectHandler];
    }
}` 

but my local MQTTClient/MinL and  MQTTClient/ManagerL already is the latest version 0.15.1, and the MQTTSessionManager "- (void)connectToInternal:(MQTTConnectHandler)connectHandler" is old version like below:
`- (void)connectToInternal:(MQTTConnectHandler)connectHandler {
    if (self.session && self.state == MQTTSessionManagerStateStarting) {
        [self updateState:MQTTSessionManagerStateConnecting];
        [self.session connectWithConnectHandler:connectHandler];
    }
}`
 

### Environment
 - Operating system:  iOS 9.0,  macOS  10.13.6
 - Software version: Xcode 9.4.1(9F2000)
 - Package Manager: Cocoapods, 1.5.3
 - MQTTClient version: Installing MQTTClient (0.15.1)

**Comment by jcavar** [comment]
There is 0.15.2 release now. Please try it out.

**Comment by ericXjj** [comment]
I have retry it，it's OK!
