### ISSUE TITLE
UnAuthorised Message delayed

### ISSUE THREAD

**Issue by RajaReddyiOS** [novastone-media/MQTT-Client-Framework#515]
am so sorry for to raising as an issue.
* I was using MQTTSessionManager, have to kick out un-authorised user, so am checking at  MqttStateDidChange delegate function. 

* Here i wont get any error message, but still i'll get last error message from sessionManager instance.
So i was kept CONNECTION_RETRY_INTERVAL to 60sec at this time-interval am getting a huge delay to parse lastErrorCode. 
* when i playing with CONNECTION_RETRY_INTERVAL to 5 sec its approximately 20-30 sec delay to get lastErrorCode.

do we any direct and quick call back to kick-out un-authorised users

**Comment by RajaReddyiOS** [comment]
> am so sorry for to raising as an issue.
> 
> * I was using MQTTSessionManager, have to kick out un-authorised user, so am checking at  MqttStateDidChange delegate function.
> * Here i wont get any error message, but still i'll get last error message from sessionManager instance.
>   So i was kept CONNECTION_RETRY_INTERVAL to 60sec at this time-interval am getting a huge delay to parse lastErrorCode.
> * when i playing with CONNECTION_RETRY_INTERVAL to 5 sec its approximately 20-30 sec delay to get lastErrorCode.
> 
> do we any direct and quick call back to kick-out un-authorised users

**Comment by RajaReddyiOS** [comment]
> am so sorry for to raising as an issue.
> 
> * I was using MQTTSessionManager, have to kick out un-authorised user, so am checking at  MqttStateDidChange delegate function.
> * Here i wont get any error message, but still i'll get last error message from sessionManager instance.
>   So i was kept CONNECTION_RETRY_INTERVAL to 60sec at this time-interval am getting a huge delay to parse lastErrorCode.
> * when i playing with CONNECTION_RETRY_INTERVAL to 5 sec its approximately 20-30 sec delay to get lastErrorCode.
> 
> do we any direct and quick call back to kick-out un-authorised users

@anagromataf @devashishmamgain @tetriscode @JakeSc

**Comment by jcavar** [comment]
Isn't this related to keep alive instead of connection retry?
