### ISSUE TITLE
Feature Request: Disable Reconnect in MQTTSessionManager

### ISSUE THREAD

**Issue by kachi1227** [novastone-media/MQTT-Client-Framework#517]
It'd be really helpful if there was a way to disable automatic reconnect in MQTTSessionManager so that developers who wanted to implement their own reconnect mechanism could do so and still leverage the benefits of MQTTSessionManager.

I have a particular use case where I'd like to attempt a one-shot connection to the MQTT broker. If that connection attempt fails, I would like to handle reconnection on my own under my own conditions; right now that's not possible using MQTTSessionManager.

**Comment by jcavar** [comment]
What are other major benefits of `MQTTSessionManager` apart from reconnection handling?
