### ISSUE TITLE
Random Crash in [MQTTCFSocketEncoder stream:handleEvent:] and [MQTTCoreDataPersistence managedObjectContext] and [MQTTCoreDataPersistence allFlowsforClientId:incomingFlag:]

### ISSUE THREAD

**Issue by ayzhangqiao** [novastone-media/MQTT-Client-Framework#522]
### Short description
Our project has been running for a while, but we've seen a lot of random crashes on some frabic like crash statistics platforms. We checked the system and equipment of the crashed model and found no fixed rules. In addition, our MQTT link is not in the UI thread, so I don't know if this is a risk point.

### Environment

 - Operating system:  iOS 
 - Software version: iOS 9.3.5 - 12.1.4 
 - Package Manager: Manual 
 - MQTTClient version: 0.15.2

### crash info

<img width="970" alt="屏幕快照 2019-03-11 11 29 12" src="https://user-images.githubusercontent.com/15105736/54111280-7f7b3780-441e-11e9-891d-f8184c115acf.png">
<img width="858" alt="屏幕快照 2019-03-11 11 24 24" src="https://user-images.githubusercontent.com/15105736/54111283-80ac6480-441e-11e9-90cb-876acc37ccb3.png">
<img width="1194" alt="屏幕快照 2019-03-11 11 30 14" src="https://user-images.githubusercontent.com/15105736/54111286-8144fb00-441e-11e9-9da8-772a4a94c719.png">

**Comment by Dongxi729** [comment]
我们也是诶 哎 醉了，感觉他们都不维护这个框架了 ，好坑。后面你怎么解决的？兄台？能赐教吗？
