### ISSUE TITLE
MQTTSessionManager ans Websockets

### ISSUE THREAD

**Issue by jannietheron** [novastone-media/MQTT-Client-Framework#528]
### Short description
Is it possible to use the SessionManager over a WebSocket connection ? I can successfully connect using MQTTWebsocketTransport, but is there a way to use it with the manager. Having the reconnect and resubscribe would spare me a lot of code.

### Environment
 - Operating system:  iOS
 - Software version: 12
 - Package Manager: Cocoapods
 - MQTTClient version: 0.15.2
 - MQTT Broker used: mosquitto

### Expected behaviour
Inject either transport or session to the manager

**Comment by jcavar** [comment]
It is unfortunately not possible to use session manager over web socket. 
I think this is reasonable request but I am afraid that design of session manager doesn't allow us to do this at the moment.

**Comment by jannietheron** [comment]
Thanks. I started implementing a MQTTTransport implementing client using Starscream library

**Comment by jcavar** [comment]
Great, I will close this issue for now then.
