### ISSUE TITLE
CocoaLumberjack conflict 

### ISSUE THREAD

**Issue by ameue** [novastone-media/MQTT-Client-Framework#535]
### Short description

Before using cocoapods to introduce MQTT-Client-Framework, I introduced CocoaLumberjack with cocoapods in my project. I set static const int ddLogLevel = LOG_LEVEL in the .pch file; but I reported an error like DDLogFlag redefine confict during the compilation process.
### Environment

 - Operating system:  iOS
 - Software version: iOS12
 - Package Manager: Cocoapods
 - MQTTClient version: 0.15.2

### Link to logs

Create a [GIST](https://gist.github.com) which is a paste of your logs, and link them here. 
Please do _NOT_ paste your full logs here, it will make issue very long and hard to read! 

### Steps to reproduce

1. Podfile: A
    pod 'CocoaLumberjack'
    pod 'MQTTClient/MinL'
    pod 'MQTTClient/ManagerL'
or B
    pod 'CocoaLumberjack'
    pod 'MQTTClient'
2. pod install
3. command+B
4. Using A way to compile will give an error: Redeclaration of 'ddLogLevel' with a different type: 'DDLogLevel' (aka 'enum DDLogLevel') vs 'const int'
5. Using B way to compile will give an error:DDLogFlag redefine confict
### Actual behaviour

no log
### Other information

I have introduced #import <CocoaLumberjack/CocoaLumberjack.h> in the .pch file and set static const int ddLogLevel = DDLogLevelDebug;. I don't want to comment out the #import <MQTTClient / MQTTLog.h> line in the MQTTClient.h file imported by Pods.xcodeproj, I don't want to manually comment this line every time pod install. Is there any other better way to resolve this compilation conflict?
If there is no good solution, I only have to manually import the mqtt source into the project, and then comment out the line that imports the log header file. This way, updating the mqtt version is not convenient with cocoapods.

**Comment by jcavar** [comment]
See https://github.com/novastone-media/MQTT-Client-Framework/issues/531

**Comment by ameue** [comment]
> See #531

This does not work

**Comment by ameue** [comment]
> See #531

This does not work
